api-v1:
  - changed-files:
      - any-glob-to-any-file:
          - "app/main.py"
          - "app/aoml.py"

api-v2:
  - changed-files:
      - any-glob-to-any-file: "app/v2.py"

data:
  - changed-files:
      - any-glob-to-any-file:
          - "app/store.py"
          - "app/dump_loader.py"

tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - ".dockerignore"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "requirements.txt"
          - "requirements-dev.txt"
